#+TITLE: articlelink
#+AUTHOR: Matt Teichman
#+DESCRIPTION: REST API for retrieving journal article link from SFX
#+OPTIONS: toc:nil, num:nil

=articlelink= is a web service for retrieving links to journal
articles via the UChicago Library's installation of [[https://en.wikipedia.org/wiki/SFX_(software)][SFX]].  The SFX API
already provides this functionality, but it returns a hard-to-read XML
response containing lots of irrelevant data.  =articlelink= cleans the
response from the SFX API up and puts it into a human-readable JSON
document.  It is intended for use on the backend by UChicago Library
web applications, though it is technically possible for an end user to
run it as well.

* Design

Here are a few highlights:

+ for convenience, if =articlelink= is given a command line argument,
  it percent escapes the command line argument for copying/pasting
  into a query string
+ otherwise, =articlelink= runs as a CGI, under Apache in our
  production environment
+ it listens for GET requests only

* Quickstart

** Build

To build, install =opam= through your OS package manager.

#+begin_example
  $ cd /path/to/source/repo
  $ make sandbox
#+end_example

** Run

#+begin_example
  $ cd /path/to/source/repo
  $ dune exec articlelink -- "https://sfx.lib.uchicago.edu/sfx_local?url_ver=Z39.88-2004&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&genre=article&sid=ProQ:ProQ%3Apq1busgeneral&atitle=Asymmetric+Information+and+Portfolio+Performance+Measurement&title=Journal+of+Financial+Economics&issn=0304405X&date=1979-12-01&volume=7&issue=4&spage=381&au=Cornell%2C+Bradford&isbn=&jtitle=Journal+of+Financial+Economics&btitle=&rft_id=info:eric/00115427&rft_id=info:doi/"
  openurl=https://sfx.lib.uchicago.edu/sfx_local?url_ver=Z39.88-2004%26rft_val_fmt=info:ofi/fmt:kev:mtx:journal%26genre=article%26sid=ProQ:ProQ%253Apq1busgeneral%26atitle=Asymmetric%2BInformation%2Band%2BPortfolio%2BPerformance%2BMeasurement%26title=Journal%2Bof%2BFinancial%2BEconomics%26issn=0304405X%26date=1979-12-01%26volume=7%26issue=4%26spage=381%26au=Cornell%252C%2BBradford%26isbn=%26jtitle=Journal%2Bof%2BFinancial%2BEconomics%26btitle=%26rft_id=info:eric/00115427%26rft_id=info:doi/
  $ env QUERY_STRING="openurl=https://sfx.lib.uchicago.edu/sfx_local?url_ver=Z39.88-2004%26rft_val_fmt=info:ofi/fmt:kev:mtx:journal%26genre=article%26sid=ProQ:ProQ%253Apq1busgeneral%26atitle=Asymmetric%2BInformation%2Band%2BPortfolio%2BPerformance%2BMeasurement%26title=Journal%2Bof%2BFinancial%2BEconomics%26issn=0304405X%26date=1979-12-01%26volume=7%26issue=4%26spage=381%26au=Cornell%252C%2BBradford%26isbn=%26jtitle=Journal%2Bof%2BFinancial%2BEconomics%26btitle=%26rft_id=info:eric/00115427%26rft_id=info:doi/" dune exec articlelink
  Status: 200
  Content-Type: application/json

  { "hits":
      [ { "provider": "Elsevier ScienceDirect Journals",
          "link":
            "https://proxy-redirector.lib.uchicago.edu/login?url=https%3A%2F%2Fwww.sciencedirect.com%2Fscience%3F_ob%3DGatewayURL%26_origin%3DSFX%26_method%3DcitationSearch%26_volkey%3D0304405X%25237%2523381%25234%26_version%3D1%26md5%3D06cd0c49a9e04c7bd4c8bfc759d4f0a3" },
        { "provider": "Elsevier SD Backfile Economics",
          "link":
            "https://proxy-redirector.lib.uchicago.edu/login?url=https%3A%2F%2Fwww.sciencedirect.com%2Fscience%3F_ob%3DGatewayURL%26_origin%3DSFX%26_method%3DcitationSearch%26_volkey%3D0304405X%25237%2523381%25234%26_version%3D1%26md5%3D06cd0c49a9e04c7bd4c8bfc759d4f0a3" } ] }
#+end_example

** Curl

To test with =curl=, first install =althttpd=.

#+begin_example
  $ cd /path/to/source/repo
  $ dune exec articlelink -- "https://sfx.lib.uchicago.edu/sfx_local?url_ver=Z39.88-2004&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&genre=article&sid=ProQ:ProQ%3Apq1busgeneral&atitle=Asymmetric+Information+and+Portfolio+Performance+Measurement&title=Journal+of+Financial+Economics&issn=0304405X&date=1979-12-01&volume=7&issue=4&spage=381&au=Cornell%2C+Bradford&isbn=&jtitle=Journal+of+Financial+Economics&btitle=&rft_id=info:eric/00115427&rft_id=info:doi/"
  $ make serve
  $ curl -i "http://localhost:3000/articlelink?openurl=https://sfx.lib.uchicago.edu/sfx_local?url_ver=Z39.88-2004%26rft_val_fmt=info:ofi/fmt:kev:mtx:journal%26genre=article%26sid=ProQ:ProQ%253Apq1busgeneral%26atitle=Asymmetric%2BInformation%2Band%2BPortfolio%2BPerformance%2BMeasurement%26title=Journal%2Bof%2BFinancial%2BEconomics%26issn=0304405X%26date=1979-12-01%26volume=7%26issue=4%26spage=381%26au=Cornell%252C%2BBradford%26isbn=%26jtitle=Journal%2Bof%2BFinancial%2BEconomics%26btitle=%26rft_id=info:eric/00115427%26rft_id=info:doi/"
  HTTP/1.1 200
  Content-Type: application/json
  Content-length: 705

  { "hits":
      [ { "provider": "Elsevier ScienceDirect Journals",
          "link":
            "https://proxy-redirector.lib.uchicago.edu/login?url=https%3A%2F%2Fwww.sciencedirect.com%2Fscience%3F_ob%3DGatewayURL%26_origin%3DSFX%26_method%3DcitationSearch%26_volkey%3D0304405X%25237%2523381%25234%26_version%3D1%26md5%3D06cd0c49a9e04c7bd4c8bfc759d4f0a3" },
        { "provider": "Elsevier SD Backfile Economics",
          "link":
            "https://proxy-redirector.lib.uchicago.edu/login?url=https%3A%2F%2Fwww.sciencedirect.com%2Fscience%3F_ob%3DGatewayURL%26_origin%3DSFX%26_method%3DcitationSearch%26_volkey%3D0304405X%25237%2523381%25234%26_version%3D1%26md5%3D06cd0c49a9e04c7bd4c8bfc759d4f0a3" } ] }
#+end_example

* Interface

=articlelink= has one mandatory query string parameter:

+ =openurl=: a full SFX openurl string (must be correctly percent
  escaped)

It also accepts the following two optional query string parameters:

+ =callback=: a callback input, for front-ends that expect a [[https://en.wikipedia.org/wiki/JSONP][JSONP]]
  rather than JSON response

+ =xml=: a boolean field; if =xml= is set to =true=, then
  =articlelink= returns the raw XML response from SFX (for debugging
  only)

* Output Format

+ normally, =articlelink= returns a JSON response with the following structure:

  #+begin_example
    HTTP/1.1 200
    Content-Type: application/json
    Content-length: 705

    { "hits":
        [ { "provider": "provider name",
            "link":
              "https://link.to/the/article" },
          { "provider": "another provider name",
            "link":
              "https://link.to/another/article" } ] }
  #+end_example

+ if there is an error, it returns a JSON response with this structure:

  #+begin_example
    HTTP/1.1 400
    Content-Type: application/json
    Content-length: 50

    { "error": "error message here" }
  #+end_example

+ if the =xml= query string parameter is set to =true=, it returns an
  XML response:

  #+begin_example
    HTTP/1.1 200
    Content-Type: application/xml
    Content-length: 21656

    <?xml version="1.0" encoding="utf-8"?>
    <big_disgusting_xml_blob>
    </big_disgusting_xml_blbo>
  #+end_example
